[package]
name = "dicom-miner"
version = "0.1.0"
edition = "2021"

[dependencies]
dicom = "0.7.0"
dicom-json = "0.7.0"
serde_json = "1.0"
arrow = "51.0.0"
parquet = { version = "51.0.0", features = ["arrow", "async", "zstd"] }
crossbeam-channel = "0.5"
indicatif = { version = "0.17", features = ["rayon"] }
clap = { version = "4.5", features = ["derive"] }
rayon = "1.10"
rust_search = "2.1"
log = "0.4"
thiserror = "1.0"
env_logger = "0.11"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
snafu = "0.8"
chrono = "=0.4.38"

[dev-dependencies]
tempfile = "3.10"
dicom-test-files = "0.3"
rstest = "0.19"

[[bin]]
name = "dicom-miner"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = "fat"
